#!/bin/sh

# Arguments are required
if [ -z $1 ] ; then
	echo "Usage: curvall <directory> [<process>]"
	exit
fi
if [ -z $2 ] ; then
	PROCESS=curve
else
	PROCESS=$2
fi

for IMG in `ls $1`
do
	./curvr $1/$IMG $PROCESS $1/`echo $PROCESS $IMG | sed 's/\(.*\) \([a-zA-Z0-9_][a-zA-Z0-9_]*\)\(\.[a-zA-Z][a-zA-Z]*\)/\2_\1\3/'`
done
